export const IMG_PATH = {
  FLOWER: {
    AutumnSymphony: require('@assets/img/flower/AutumnSymphony.jpg'),
    BlazingBlassoms: require('@assets/img/flower/BlazingBlassoms.jpg'),
    BlueHarmony: require('@assets/img/flower/BlueHarmony.jpg'),
    DawnsDelight: `/img/flower/DawnsDelight.jpg`,
    DriedFlowers: require('@assets/img/flower/DriedFlowers.jpg'),
    LivePlants: require('@assets/img/flower/LivePlants.jpg'),
    MysticalMajesty: require('@assets/img/flower/MysticalMajesty.jpg'),
    PinkElegance: require('@assets/img/flower/PinkElegance.jpg'),
    ProductPageFlower: require('@assets/img/flower/ProductPageFlower.jpg'),
    RosyDelight: require('@assets/img/flower/RosyDelight.jpg'),
    RusticCharm: require('@assets/img/flower/RusticCharm.jpg'),
    Serenity: require('@assets/img/flower/Serenity.jpg'),
    Snowfall: require('@assets/img/flower/Snowfall.jpg'),
    ThreeClassic: require('@assets/img/flower/ThreeClassic.jpg'),
    ThreeLuxe: require('@assets/img/flower/ThreeLuxe.jpg'),
    ThreeSeasonal: require('@assets/img/flower/ThreeSeasonal.jpg'),
  },
  OTHER: {
    AromaCandels: require('@assets/img/other/AromaCandels.jpg'),
    Bamboo: require('@assets/img/other/Bamboo.jpg'),
    BgGrayPerson: require('@assets/img/other/BgGrayPerson.jpg'),
    CedarLavender: require('@assets/img/other/Cedar&Lavender.jpg'),
    CeramicVase: require('@assets/img/other/CeramicVase.jpg'),
    Company: require('@assets/img/other/Company.jpg'),
    Female: require('@assets/img/other/Female.jpg'),
    FlowerArrangement: require('@assets/img/other/FlowerArrangement.jpg'),
    Fresheners: require('@assets/img/other/Fresheners.jpg'),
    FreshFlowers: require('@assets/img/other/FreshFlowers.jpg'),
    GlassVase: require('@assets/img/other/GlassVase.jpg'),
    Hammershoi: require('@assets/img/other/Hammershoi.jpg'),
    HighHeelsSofa: require('@assets/img/other/HighHeelsSofa.jpg'),
    LimeMatcha: require('@assets/img/other/Lime&Matcha.jpg'),
    LivingRoomSofa: require('@assets/img/other/LivingRoomSofa.jpg'),
    OceanMist: require('@assets/img/other/OceanMist.jpg'),
    RattanGrapefruit: require('@assets/img/other/RattanGrapefruit.jpg'),
    RedFlowerPerson: require('@assets/img/other/RedFlowerPerson.jpg'),
    SteelVase: require('@assets/img/other/SteelVase.jpg'),
    Temple: require('@assets/img/other/Temple.jpg'),
    WhiteFlowerPerson: require('@assets/img/other/WhiteFlowerPerson.jpg'),
  },
};
