export const IMG_PATH = {
  FLOWER: {
    AutumnSymphony: '/img/flower/AutumnSymphony.jpg',
    BlazingBlassoms: '/img/flower/BlazingBlassoms.jpg',
    BlueHarmony: '/img/flower/BlueHarmony.jpg',
    DawnsDelight: `/img/flower/Dawn'sDelight.jpg`,
    DriedFlowers: '/img/flower/DriedFlowers.jpg',
    LivePlants: '/img/flower/LivePlants.jpg',
    MysticalMajesty: '/img/flower/MysticalMajesty.jpg',
    PinkElegance: '/img/flower/PinkElegance.jpg',
    ProductPageFlower: '/img/flower/ProductPageFlower.jpg',
    RosyDelight: '/img/flower/RosyDelight.jpg',
    RusticCharm: '/img/flower/RusticCharm.jpg',
    Serenity: '/img/flower/Serenity.jpg',
    Snowfall: '/img/flower/Snowfall.jpg',
    ThreeClassic: '/img/flower/ThreeClassic.jpg',
    ThreeLuxe: '/img/flower/ThreeLuxe.jpg',
    ThreeSeasonal: '/img/flower/ThreeSeasonal.jpg',
  },
  OTHER: {
    AromaCandels: '/img/other/AromaCandels.jpg',
    Bamboo: '/img/other/Bamboo.jpg',
    BgGrayPerson: '/img/other/BgGrayPerson.jpg',
    CedarLavender: '/img/other/Cedar&Lavender.jpg',
    CeramicVase: '/img/other/CeramicVase.jpg',
    Company: '/img/other/Company.jpg',
    Female: '/img/other/Female.jpg',
    FlowerArrangement: '/img/other/FlowerArrangement.jpg',
    Fresheners: '/img/other/Fresheners.jpg',
    FreshFlowers: '/img/other/FreshFlowers.jpg',
    GlassVase: '/img/other/GlassVase.jpg',
    Hammershoi: '/img/other/Hammershoi.jpg',
    HighHeelsSofa: '/img/other/HighHeelsSofa.jpg',
    LimeMatcha: '/img/other/Lime&Matcha.jpg',
    LivingRoomSofa: '/img/other/LivingRoomSofa.jpg',
    OceanMist: '/img/other/OceanMist.jpg',
    RattanGrapefruit: '/img/other/RattanGrapefruit.jpg',
    RedFlowerPerson: '/img/other/RedFlowerPerson.jpg',
    SteelVase: '/img/other/SteelVase.jpg',
    Temple: '/img/other/Temple.jpg',
    WhiteFlowerPerson: '/img/other/WhiteFlowerPerson.jpg',
  },
};
